### ISSUE TITLE
AttributeError: 'BARFHashField' object has no attribute 'mlp_base_grid'

### ISSUE THREAD

**Issue by geyang** [maturk/BARF-nerfstudio#1]
After installation ran 

```shell
ns-train --barf-grid --data <data_path>
```

and get the following error

```shell
AttributeError: 'BARFHashField' object has no attribute 'mlp_base_grid'
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.0461
VanillaPipeline.get_train_loss_dict: 0.0457
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/mit/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/user/mit/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/user/mit/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/mit/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/user/mit/nerfstudio/nerfstudio/engine/trainer.py", line 261, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/user/mit/nerfstudio/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/user/mit/nerfstudio/nerfstudio/engine/trainer.py", line 496, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/user/mit/nerfstudio/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/user/mit/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 301, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/home/user/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/mit/nerfstudio/nerfstudio/models/base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "/home/user/mit/BARF-nerfstudio/barf/barf.py", line 446, in get_outputs
    field_outputs = self.field.forward(ray_samples, compute_normals=self.config.predict_normals)
  File "/home/user/mit/nerfstudio/nerfstudio/fields/base_field.py", line 124, in forward
    density, density_embedding = self.get_density(ray_samples)
  File "/home/user/mit/BARF-nerfstudio/barf/barf_field.py", line 228, in get_density
    hashgrid_vecs = self.mlp_base_grid(positions_flat)
  File "/home/user/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'BARFHashField' object has no attribute 'mlp_base_grid'
```

**Comment by andrewyguo** [comment]
you have to change it to use 'mlp_base' instead of 'mlp_base_grid'. This attribute was updated in nerfstudio sometime ago

**Comment by maturk** [comment]
@andrewyguo , yeah this repo is quite out of date now. Feel free to make a PR if you have fixes.

**Comment by andrewyguo** [comment]
@maturk I ran into this other issue while trying to run `barf-hash`. (`barf-freq` and `barf-grad` work fine) Do you know a fix? 


```
$ ns-train barf-hash --data data/plant/


[14:39:39] Using --data alias for --data.pipeline.datamanager.data                                          train.py:230
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=PosixPath('outputs'),
    method_name='barf-hash',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-09-26_143939',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=BARFPipelineConfig(
        _target=<class 'barf.barf_pipeline.BARFPipeline'>,
        datamanager=VanillaDataManagerConfig(
            _target=<class 'nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager'>,
            data=PosixPath('data/plant'),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=NerfstudioDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>,
                data=PosixPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                eval_mode='fraction',
                train_split_fraction=0.9,
                eval_interval=8,
                depth_unit_scale_factor=0.001,
                mask_color=None,
                load_3D_points=False
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7f7ef0bcfc10>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            camera_optimizer=None,
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False,
                ignore_mask=False,
                fisheye_crop_radius=None,
                rejection_sample_mask=True,
                max_num_iterations=100
            )
        ),
        model=BARFHashModelConfig(
            _target=<class 'barf.barf.BARFHashModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_appearance_embedding=True,
            use_average_appearance_embedding=False,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            average_init_density=1.0,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            ),
            bundle_adjust=True,
            coarse_to_fine_iters=(0.0, 0.1)
        ),
        vis_config=PosesConfig(
            save_poses=(True,),
            cam_depth=1.0,
            xlim=(-3, 3),
            ylim=(-3, 3),
            zlim=(-3, 2.4),
            poses_dir='/nfs/horai.dgpsrv/ondemand28/ykguo/BARF-nerfstudio/poses'
        )
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0001,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'fields': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0001,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'camera_opt': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=1e-07,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        }
    },
    vis='viewer',
    data=PosixPath('data/plant'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=2000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={},
    start_paused=False
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           Saving config to: outputs/plant/barf-hash/2024-09-26_143939/config.yml               experiment_config.py:136
           Saving checkpoints to: outputs/plant/barf-hash/2024-09-26_143939/nerfstudio_models             trainer.py:142
           Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:484
Setting up training dataset...
Caching all 107 images.
Setting up evaluation dataset...
Caching all 11 images.
implementation:  tcnn
implementation:  tcnn
╭─────────────── viser ────────────────╮
│             ╷                        │
│   HTTP      │ http://0.0.0.0:46631   │
│   Websocket │ ws://0.0.0.0:46631     │
│             ╵                        │
╰──────────────────────────────────────╯
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.5045              
VanillaPipeline.get_train_loss_dict: 0.5025              
Traceback (most recent call last):
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/engine/trainer.py", line 266, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/utils/profiler.py", line 111, in inner
    out = func(*args, **kwargs)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/engine/trainer.py", line 502, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/utils/profiler.py", line 111, in inner
    out = func(*args, **kwargs)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/models/base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/BARF-nerfstudio/barf/barf.py", line 448, in get_outputs
    field_outputs = self.field.forward(ray_samples, compute_normals=self.config.predict_normals)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/fields/base_field.py", line 124, in forward
    density, density_embedding = self.get_density(ray_samples)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/BARF-nerfstudio/barf/barf_field.py", line 230, in get_density
    h = self.mlp_base(hashgrid_vecs).view(*ray_samples.frustums.shape, -1)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/horai.dgpsrv/ondemand28/ykguo/nerfstudio/nerfstudio/field_components/mlp.py", line 300, in forward
    result = self.model(in_tensor)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/tinycudann/modules.py", line 190, in forward
    output = _module_function.apply(
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/scratch/ondemand28/ykguo/.conda/envs/ns/lib/python3.8/site-packages/tinycudann/modules.py", line 102, in forward
    native_ctx, output = native_tcnn_module.fwd(input, params)
RuntimeError: /tmp/pip-req-build-okh16v5g/bindings/torch/tinycudann/bindings.cpp:88 check failed input.size(1) == n_input_dims()
```
